# Generated by Django 3.2.10 on 2021-12-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120, verbose_name='Название услуги')),
                ('Icon', models.ImageField(upload_to='service/icon', verbose_name='Изображение')),
                ('Image', models.ImageField(upload_to='service/image', verbose_name='Изображение')),
                ('About', models.TextField(verbose_name='Описание')),
                ('Price', models.IntegerField(blank=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
