# Generated by Django 3.2.10 on 2022-01-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, verbose_name='Название')),
                ('Description', models.TextField(blank=True, verbose_name='Описание')),
                ('File', models.FileField(upload_to='file/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='Icon',
            field=models.ImageField(upload_to='service/icon', verbose_name='Иконка'),
        ),
    ]
