# Generated by Django 3.2.10 on 2022-01-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=120, verbose_name='Услуга')),
                ('Name', models.CharField(max_length=120, verbose_name='Имя')),
                ('Email', models.CharField(max_length=120, verbose_name='Email')),
                ('Phone', models.CharField(max_length=120, verbose_name='Телефон')),
                ('Message', models.TextField(blank=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='Phone',
            field=models.CharField(max_length=120, verbose_name='Телефон'),
        ),
    ]
